# TCL File Generated by Component Editor 23.1
# Tue Dec 03 11:57:15 MST 2024
# DO NOT MODIFY


# 
# pwm_rgb_led_controller "pwm_rgb_led_controller" v1.0
#  2024.12.03.11:57:15
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module pwm_rgb_led_controller
# 
set_module_property DESCRIPTION ""
set_module_property NAME pwm_rgb_led_controller
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME pwm_rgb_led_controller
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL pwm_rgb_controller_avalon
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file pwm_rgb_controller_avalon.vhd VHDL PATH ../hdl/pwm_rgb_controller/pwm_rgb_controller_avalon.vhd TOP_LEVEL_FILE
add_fileset_file pwm_controller.vhd VHDL PATH ../hdl/pwm_rgb_controller/pwm_controller.vhd


# 
# parameters
# 


# 
# display items
# 


# 
# connection point pwm_rgb_controller_avalon_slave
# 
add_interface pwm_rgb_controller_avalon_slave avalon end
set_interface_property pwm_rgb_controller_avalon_slave addressUnits WORDS
set_interface_property pwm_rgb_controller_avalon_slave associatedClock clk
set_interface_property pwm_rgb_controller_avalon_slave associatedReset rst
set_interface_property pwm_rgb_controller_avalon_slave bitsPerSymbol 8
set_interface_property pwm_rgb_controller_avalon_slave burstOnBurstBoundariesOnly false
set_interface_property pwm_rgb_controller_avalon_slave burstcountUnits WORDS
set_interface_property pwm_rgb_controller_avalon_slave explicitAddressSpan 0
set_interface_property pwm_rgb_controller_avalon_slave holdTime 0
set_interface_property pwm_rgb_controller_avalon_slave linewrapBursts false
set_interface_property pwm_rgb_controller_avalon_slave maximumPendingReadTransactions 0
set_interface_property pwm_rgb_controller_avalon_slave maximumPendingWriteTransactions 0
set_interface_property pwm_rgb_controller_avalon_slave readLatency 0
set_interface_property pwm_rgb_controller_avalon_slave readWaitTime 1
set_interface_property pwm_rgb_controller_avalon_slave setupTime 0
set_interface_property pwm_rgb_controller_avalon_slave timingUnits Cycles
set_interface_property pwm_rgb_controller_avalon_slave writeWaitTime 0
set_interface_property pwm_rgb_controller_avalon_slave ENABLED true
set_interface_property pwm_rgb_controller_avalon_slave EXPORT_OF ""
set_interface_property pwm_rgb_controller_avalon_slave PORT_NAME_MAP ""
set_interface_property pwm_rgb_controller_avalon_slave CMSIS_SVD_VARIABLES ""
set_interface_property pwm_rgb_controller_avalon_slave SVD_ADDRESS_GROUP ""

add_interface_port pwm_rgb_controller_avalon_slave avs_read read Input 1
add_interface_port pwm_rgb_controller_avalon_slave avs_write write Input 1
add_interface_port pwm_rgb_controller_avalon_slave avs_address address Input 2
add_interface_port pwm_rgb_controller_avalon_slave avs_readdata readdata Output 32
add_interface_port pwm_rgb_controller_avalon_slave avs_writedata writedata Input 32
set_interface_assignment pwm_rgb_controller_avalon_slave embeddedsw.configuration.isFlash 0
set_interface_assignment pwm_rgb_controller_avalon_slave embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment pwm_rgb_controller_avalon_slave embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment pwm_rgb_controller_avalon_slave embeddedsw.configuration.isPrintableDevice 0


# 
# connection point clk
# 
add_interface clk clock end
set_interface_property clk clockRate 0
set_interface_property clk ENABLED true
set_interface_property clk EXPORT_OF ""
set_interface_property clk PORT_NAME_MAP ""
set_interface_property clk CMSIS_SVD_VARIABLES ""
set_interface_property clk SVD_ADDRESS_GROUP ""

add_interface_port clk clk clk Input 1


# 
# connection point rst
# 
add_interface rst reset end
set_interface_property rst associatedClock clk
set_interface_property rst synchronousEdges DEASSERT
set_interface_property rst ENABLED true
set_interface_property rst EXPORT_OF ""
set_interface_property rst PORT_NAME_MAP ""
set_interface_property rst CMSIS_SVD_VARIABLES ""
set_interface_property rst SVD_ADDRESS_GROUP ""

add_interface_port rst rst reset Input 1


# 
# connection point rgb_pwm
# 
add_interface rgb_pwm conduit end
set_interface_property rgb_pwm associatedClock clk
set_interface_property rgb_pwm associatedReset ""
set_interface_property rgb_pwm ENABLED true
set_interface_property rgb_pwm EXPORT_OF ""
set_interface_property rgb_pwm PORT_NAME_MAP ""
set_interface_property rgb_pwm CMSIS_SVD_VARIABLES ""
set_interface_property rgb_pwm SVD_ADDRESS_GROUP ""

add_interface_port rgb_pwm red_out red_out Output 1
add_interface_port rgb_pwm green_out green_out Output 1
add_interface_port rgb_pwm blue_out blue_out Output 1

